import React from 'react';
import { RouteAlternativeCard } from './RouteAlternativeCard';
import { SectionPanel } from '../common/SectionPanel';
import { StatusBadge } from '../common/StatusBadge';
import { EmptyState } from '../common/EmptyState';

/**
 * RouteComparisonPanel component.
 * Displays road-network route alternatives returned by the routing engine,
 * enabling users to inspect metrics and select active routes on the map.
 */
export function RouteComparisonPanel({
  routes = [],
  selectedRouteId = null,
  onSelectRoute,
  onPlanRequest,
  onClearRoutes,
}) {
  return (
    <SectionPanel
      title="Calculated Route Alternatives"
      subtitle="Road-network corridors generated from OpenStreetMap routing engine"
      badge={<StatusBadge label="PHASE 6 ROUTE ENGINE" variant="status" />}
      action={
        routes && routes.length > 0 && onClearRoutes ? (
          <button
            type="button"
            onClick={onClearRoutes}
            className="btn btn-subtle btn-sm"
            style={{ fontSize: '0.72rem', padding: '2px 8px' }}
          >
            Clear Routes
          </button>
        ) : null
      }
    >
      {routes && routes.length > 0 ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
          {routes.map((route) => {
            const isSelected = selectedRouteId
              ? route.route_id === selectedRouteId
              : route.is_selected;

            return (
              <RouteAlternativeCard
                key={route.route_id}
                route={route}
                isSelected={isSelected}
                onSelect={(routeId) => onSelectRoute && onSelectRoute(routeId)}
              />
            );
          })}

          {/* Provider & Methodology Attribution Box */}
          <div
            style={{
              background: 'var(--color-surface-card)',
              border: '1px solid var(--color-border-subtle)',
              borderRadius: 'var(--radius-sm)',
              padding: 'var(--space-3) var(--space-4)',
              fontSize: '0.78rem',
              color: 'var(--color-text-secondary)',
              lineHeight: 1.45,
            }}
          >
            <div style={{ fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: '4px' }}>
              ℹ️ Routing Engine Notice:
            </div>
            <div>
              Route geometries and travel duration estimates are generated by OpenStreetMap / OSRM.
              Free-flow travel time is estimated without live traffic sensors.
              Micro-level safety scoring (illumination, CCTV, and verified crowd reports) will be computed in Phase 7.
            </div>
          </div>
        </div>
      ) : (
        <EmptyState
          icon="🗺️"
          title="No Route Alternatives Calculated"
          description="Enter an origin and destination in the journey form above to generate and compare real road routes across Chennai."
          actionLabel="Load Chennai Corridor Preset"
          onAction={onPlanRequest}
        />
      )}
    </SectionPanel>
  );
}
