import test from 'node:test';
import assert from 'node:assert/strict';

test('Routing Geometry: Correctly converts GeoJSON [lng, lat] coordinates to Leaflet [lat, lng]', () => {
  const geojsonCoords = [
    [80.2707, 13.0827],
    [80.2650, 13.0750],
    [80.2341, 13.0418],
  ];

  // Leaflet expects [latitude, longitude]
  const leafletCoords = geojsonCoords.map(([lng, lat]) => [lat, lng]);

  assert.equal(leafletCoords.length, 3);
  assert.equal(leafletCoords[0][0], 13.0827); // lat
  assert.equal(leafletCoords[0][1], 80.2707); // lng
  assert.equal(leafletCoords[2][0], 13.0418); // lat
  assert.equal(leafletCoords[2][1], 80.2341); // lng
});

test('Routing Metrics: Distinguishes free-flow duration from live traffic', () => {
  const mockMetric = {
    distance_km: 9.48,
    duration_minutes: 10.8,
    is_live_traffic: false,
    traffic_model: 'Free-flow standard speed limits (OpenStreetMap data)',
  };

  assert.equal(mockMetric.is_live_traffic, false);
  assert.ok(mockMetric.traffic_model.includes('Free-flow'));
  assert.ok(mockMetric.distance_km > 0);
  assert.ok(mockMetric.duration_minutes > 0);
});

test('Route Alternatives: Preserves stable identifiers and selection states', () => {
  const mockAlternatives = [
    {
      route_id: 'route-osrm-1',
      title: 'FASTEST CORRIDOR',
      preference: 'FASTEST',
      is_selected: true,
      metrics: { distance_km: 9.48, duration_minutes: 10.8 },
      safety_assessment_status: 'PENDING_PHASE_7_SAFETY_SCORING',
    },
    {
      route_id: 'route-osrm-2',
      title: 'BALANCED CORRIDOR',
      preference: 'BALANCED',
      is_selected: false,
      metrics: { distance_km: 10.12, duration_minutes: 12.3 },
      safety_assessment_status: 'PENDING_PHASE_7_SAFETY_SCORING',
    },
  ];

  assert.equal(mockAlternatives.length, 2);
  assert.equal(mockAlternatives[0].is_selected, true);
  assert.equal(mockAlternatives[1].is_selected, false);

  // Switch selection
  const targetId = 'route-osrm-2';
  const updatedAlternatives = mockAlternatives.map((r) => ({
    ...r,
    is_selected: r.route_id === targetId,
  }));

  assert.equal(updatedAlternatives[0].is_selected, false);
  assert.equal(updatedAlternatives[1].is_selected, true);
});

test('Route Safety Status: Explicitly marks safety scoring as pending Phase 7', () => {
  const mockRoute = {
    route_id: 'route-osrm-safest',
    preference: 'SAFEST',
    safety_assessment_status: 'PENDING_PHASE_7_SAFETY_SCORING',
    disclaimer: 'Route geometry generated by OSRM. Safety scoring requires Phase 7.',
  };

  // Must NOT claim to be verified safe at Phase 6
  assert.equal(mockRoute.safety_assessment_status, 'PENDING_PHASE_7_SAFETY_SCORING');
  assert.ok(mockRoute.disclaimer.includes('Phase 7'));
});

test('Validation: Rejects identical origin and destination names', () => {
  const origTrim = 'Chennai Central Railway Station';
  const destTrim = 'chennai central railway station';

  const isIdentical = origTrim.trim().toLowerCase() === destTrim.trim().toLowerCase();
  assert.equal(isIdentical, true, 'Case-insensitive identical origin and destination must be rejected');
});
